# Generated by Django 6.1 on 2026-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
