# Generated by Django 6.1 on 2026-09-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_appointement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointement',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointement_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointement_time',
            new_name='appointment_time',
        ),
    ]
